account/urls.py
from django.urls import path
from .views import (
    change_password,
    login_request,
    logout_request,
    my_publications,
    profile_request,
    register_request,
    CustomPasswordReset,
    CustomPasswordResetDone,
    CustomPasswordResetConfirm,
    CustomPasswordResetComplete,
)

app_name = "account"
password_reset_config = [
    # EMAIL
    path("restablecer-contraseña", CustomPasswordReset.as_view(), name="password_reset"),
    # MSG
    path(
        "restablecer-contraseña-enviado",
        CustomPasswordResetDone.as_view(),
        name="password_reset_done",
    ),
    # NEW_PASSWORD1 AND NEW_PASSWORD2
    path(
        "restablecer-contraseña/<uidb64>/<token>/",
        CustomPasswordResetConfirm.as_view(),
        name="password_reset_confirm",
    ),
    # MSG
    path(
        "restablecer-contraseña/finalizado",
        CustomPasswordResetComplete.as_view(),
        name="password_reset_complete",
    ),
]


urlpatterns = [
    path("iniciar-sesion/", login_request, name="login"),
    path("registrarse/", register_request, name="register"),
    path("perfil/", profile_request, name="profile"),
    path("cambiar-contraseña/", change_password, name="change_password"),
    path("cerrar-sesion/", logout_request, name="logout"),
    path("mis-publicaciones/", my_publications, name="my_publications"),
    *password_reset_config,
]

my_site/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

handler404 = "pages.views.handler404"
from django.urls import re_path

# from django.conf import settings
from django.views.static import serve

url_files = [
    re_path(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
    re_path(r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_ROOT}),
]

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("pages.urls")),
    path("apuntes/", include("study_hub.urls")),
    path("cuenta/", include("account.urls")),
    path("cursos/", include("study_manager.urls")),
    path("tinymce/", include("tinymce.urls")),
]

if settings.DEBUG == False:
    urlpatterns += url_files
else:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from .views import home, searchNavbar, about_me


urlpatterns = [
    path("", home, name="home"),
    path("acerca-de-mi/", about_me, name="about"),
    # POST require
    path("search/publications/", searchNavbar, name="search"),
    # GET require
]

account/models.py
import os
from django.conf import settings
from django.core.files.storage import default_storage
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="Profile")
    avatar = models.ImageField(upload_to="avatars", default="avatars/default_avatar.png")

    @property
    def user_publications(self):
        return self.user.publications.all()

    def save(self, *args, **kwargs):
        if self.pk and self.avatar:
            old_profile = Profile.objects.get(pk=self.pk)

            if (
                "_avatar" in old_profile.avatar.name
                and old_profile.avatar.name != "avatars/default_avatar.png"
            ):
                # SI EL ARCHIVO YA EXISTE Y NO ES EL DETERMINADO, LO BORRO
                default_storage.delete(old_profile.avatar.path)

            # ESTO ES PARA CAMBIARLE EL NOMBRE AL AVATAR CREADO
            if self.avatar.name != "avatars/default_avatar.png":
                filename, ext = os.path.splitext(self.avatar.name)
                self.avatar.name = self.user.username + "_avatar" + ext
        super(Profile, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.user.username}__avatar"


# CONVIERTO Y TRANSFORMO EL TAMAÑO Y EL FORMATO DE LA IMAGEN AVATAR EN PROFILE
@receiver(post_save, sender=Profile)
def resize_avatar(sender, instance, created, **kwargs):
    if not created and instance.avatar.name != "avatars/default_avatar.png":
        image_path = os.path.join(settings.MEDIA_ROOT, str(instance.avatar.name))
        img = Image.open(image_path)
        max_size = (138, 138)
        img.thumbnail(max_size)
        img.save(instance.avatar.path)


# CREO UN OBJETO PROFILE LUEGO DE QUE SE CREE UN USER
@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm
from django.contrib.auth.models import User
from .models import Profile


class CustomAuthForm(AuthenticationForm):
    remember_me = forms.BooleanField(
        required=False, widget=forms.CheckboxInput(), label="Mantener sesión conectada"
    )


class CustomFields(forms.Form):
    def __init__(self, *args, **kwargs):
        required = kwargs.pop("required", True)  # Por defecto required es True
        super(CustomFields, self).__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.required = required

    first_name = forms.CharField(
        max_length=30,
        label="Nombre",
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "", "max-length": 30}
        ),
    )
    last_name = forms.CharField(
        max_length=30,
        label="Apellido",
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "", "max-length": 30}
        ),
    )
    email = forms.CharField(
        label="Correo electrónico",
        widget=forms.EmailInput(attrs={"class": "form-control", "placeholder": ""}),
    )


class CustomRegisterForm(UserCreationForm, CustomFields):
    class Meta:
        model = User
        fields = (
            "username",
            "first_name",
            "last_name",
            "password1",
            "password2",
            "email",
        )

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Este correo electrónico ya está en uso.")
        return email


class CustomProfileForm(CustomFields, forms.ModelForm):
    class Meta:
        model = Profile
        fields = [
            "avatar",
            "first_name",
            "last_name",
            "email",
        ]

    def save(self, commit=True):
        profile_instance = super(CustomProfileForm, self).save(commit=False)
        user_instance = profile_instance.user
        user_data = self.cleaned_data

        if any(user_data[field] for field in ["first_name", "last_name", "email"]):
            user_instance.first_name = self.cleaned_data["first_name"]
            user_instance.last_name = self.cleaned_data["last_name"]
            user_instance.email = self.cleaned_data["email"]
            user_instance.save()

        if commit:
            if not user_instance.username in profile_instance.avatar.url:
                profile_instance.save()

        return profile_instance

account/views.py
from django.contrib.auth import login, authenticate, logout, views as auth_views
from django.shortcuts import redirect, render
from django.urls import reverse_lazy

from study_hub.models import Publication

from .forms import CustomRegisterForm, CustomAuthForm
from django.contrib.auth.forms import PasswordChangeForm

from django.contrib import messages
from django.contrib.auth.decorators import login_required


from django.contrib.auth.models import User
from .models import Profile
from .forms import CustomProfileForm


from django.contrib.auth import update_session_auth_hash
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def login_request(request):
    if request.user.is_authenticated:
        messages.success(request, "Ya esta conectado!")
        return redirect(reverse_lazy("home"))

    context = {"title": "Iniciar Sesión", "site": "login", "form": CustomAuthForm}
    form = CustomAuthForm(request, request.POST)

    if request.method == "POST":
        if form.is_valid():
            user = authenticate(
                request,
                username=request.POST["username"],
                password=request.POST["password"],
            )
            if user is not None:
                login(request, user)
                if not form.cleaned_data.get("remember_me", False):
                    request.session.set_expiry(0)

                messages.success(request, "Sesión iniciada correctamente!")
                return redirect(reverse_lazy("home"))
        else:
            messages.error(request, "Usuario y/o contraseña incorrecto!")

    return render(request, "auth.html", context)


def register_request(request):
    if request.user.is_authenticated:
        messages.success(request, "Ya esta registrado!")
        return redirect(reverse_lazy("home"))

    context = {
        "title": "Crear cuenta nueva",
        "site": "register",
        "form": CustomRegisterForm,
    }

    if request.method == "POST":
        form = CustomRegisterForm(request.POST)

        if form.is_valid():
            form.save()
            user = authenticate(
                request,
                username=form.cleaned_data.get("username"),
                password=form.cleaned_data.get("password1"),
            )
            login(request, user)
            messages.success(
                request,
                "Bienvenido "
                + form.cleaned_data.get("first_name")
                + ", el registro fue exitoso!",
            )
            return redirect(reverse_lazy("home"))
        else:
            messages.error(request, "Por favor, corrija los errores del formulario.")
            context.update({"form": form})

    return render(request, "auth.html", context)


@login_required
def logout_request(request):
    logout(request)
    messages.success(request, "Se ha desconectado exitosamente!")
    return redirect(reverse_lazy("home"))


@login_required
def profile_request(request):
    user = User.objects.get(username=request.user.username)
    profile = (
        Profile.objects.get(user=user)
        if Profile.objects.filter(user=user)
        else Profile.objects.create(user=user)
    )
    if request.method == "POST":
        profile_form = CustomProfileForm(
            request.POST, request.FILES, instance=profile, required=False
        )

        if profile_form.is_valid():
            profile_form.save()
        return redirect(reverse_lazy("account:profile"))
    else:
        profile_form = CustomProfileForm(
            instance=profile,
            initial={
                "first_name": user.first_name,
                "last_name": user.last_name,
                "email": user.email,
            },
        )

    context = {
        "title": "Mi Perfil",
        "site": "profile",
        "form": profile_form,
    }
    return render(request, "auth.html", context)


@login_required
def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, "Su contraseña fue actualizada exitosamente!")
            return redirect(reverse_lazy("account:profile"))
        else:
            messages.error(request, "Por favor, corrija el o los siguientes errores.")
    else:
        form = PasswordChangeForm(request.user)
    return render(
        request,
        "auth.html",
        {"site": "change_password", "title": "Cambiar contraseña", "form": form},
    )


class CustomPasswordReset(auth_views.PasswordResetView):
    template_name = "password_reset.html"
    success_url = reverse_lazy("account:password_reset_done")
    extra_context = {"site": "password_reset"}
    email_template_name = "password_reset_email.html"

    def post(self, request, *args, **kwargs):
        email = request.POST.get("email")
        if User.objects.filter(email=email).exists():
            return super().post(request, *args, **kwargs)
        else:
            msg = f"No existe ningun usuario registrado con el siguiente correo electronico: {email}"
            messages.error(request, msg)
            return redirect(reverse_lazy("account:password_reset"))


class CustomPasswordResetDone(auth_views.PasswordResetDoneView):
    customMessages = [
        "Le enviamos las instrucciones para recuperar su cuenta por correo electrónico",
        """ Si no recibe un correo electrónico, asegúrese de haber ingresado la dirección con la que se
        registró y verifique su carpeta de correo no deseado.""",
    ]

    template_name = "password_reset.html"
    extra_context = {"customMessages": customMessages}


class CustomPasswordResetConfirm(auth_views.PasswordResetConfirmView):
    template_name = "password_reset.html"
    extra_context = {"site": "password_reset_confirm"}
    success_url = reverse_lazy("account:password_reset_complete")


class CustomPasswordResetComplete(auth_views.PasswordResetCompleteView):
    customMessages = [
        "Su contraseña ha sido restablecida exitosamente!",
        "Puede continuar e iniciar sesión ahora.",
    ]

    template_name = "password_reset.html"
    extra_context = {"customMessages": customMessages}


@login_required
def my_publications(request):
    publications_filter = Publication.objects.filter(author=request.user).order_by(
        "-publication_date"
    )
    paginator = Paginator(publications_filter, 6)
    page = request.GET.get("page")

    try:
        publications = paginator.page(page)
    except PageNotAnInteger:
        publications = paginator.page(1)
    except EmptyPage:
        publications = paginator.page(paginator.num_pages)

    return render(
        request,
        "my_publications.html",
        {"title": "Mis Publicaciones", "my_publications": publications},
    )

account/templates/partials/change_password.html
<div class="row m-0 w-100">



    <p style="line-height: 1.5em; letter-spacing: .8px;"
        class="col-sm-8 col-12 mx-auto text-center mb-3 text-secondary">Antes
        de realizar el cambio, considere que una contraseña segura debe contener una combinación de letras mayúsculas y
        minúsculas, números y caracteres especiales.</p>

    <form action="" method="POST" class="col-sm-6 col-10 mx-auto my-4 text-center bg-light shadow-lg py-5 px-sm-5 px-3 rounded"
        style="--bs-bg-opacity: .9;">

        {% csrf_token %}
        <div class="form-floating mb-2">
            <input type="password" class="form-control mb-2 {% if form.old_password.errors %}is-invalid{% endif %}"
                autofocus autocomplete="current-password" name="old_password" id="id_old_password" placeholder="">
            {{form.old_password.label_tag}}
            <span class="small text-danger"> {{form.old_password.errors}} </span>
        </div>
        <hr>
        <div class="form-floating mb-2">
            <input type="password"
                class="form-control mb-2 {% if form.new_password1.errors or form.new_password2.errors %}is-invalid{% endif %}"
                name="new_password1" autocomplete="off" id="id_new_password1" placeholder="password">
            {{form.new_password1.label_tag}}
            <span class="small text-danger"> {{form.new_password1.errors}} </span>
        </div>

        <div class="form-floating mb-2">
            <input
                class="form-control mb-2 {% if form.new_password1.errors or form.new_password2.errors %}is-invalid{% endif %}"
                type="password" name="new_password2" autocomplete="off" id="id_new_password2" placeholder="password">
            {{form.new_password2.label_tag}}
            <span class="small text-danger"> {{form.new_password2.errors}} </span>
        </div>



        <a href="{% url 'account:profile' %}" class="btn btn-outline-danger me-2">Cancelar</a>
        <input type="submit" value="Cambiar contraseña" class="my-3 btn btn-primary">
    </form>

</div>

account/templates/partials/login.html
{% load static %}


<form method="post" class="text-center container mb-5" style="width: 330px;">
    <div class="bg-secondary-subtle rounded-circle mx-auto mt-2 mb-4 px-3 py-4 text-center border border-light shadow-lg"
        style="width: fit-content; height: fit-content;">
        <img style="margin-left:1rem" src="{% static 'images/decoration/gohan-head.png' %}" alt="user-anonymous">
    </div>

    {% csrf_token %}

    <input class="form-control mb-2" required autocomplete="username" autofocus type="text" name="username"
        placeholder="{{form.username.label}}" id="id_username">
    <input class="form-control mb-2" required autocomplete="current-password" type="password" name="password"
        placeholder="{{form.password.label}}" id="id_password">

    <div class="my-3">
        <label class="form-check-label small text-secondary me-2" for="id_remember_me">Recordarme</label>
        <input class="form-check-input" type="checkbox" name="remember_me" id="id_remember_me" checked>
    </div>

    <input type="submit" value="Iniciar Sesión" class="btn btn-primary">

    <div class="text-center mt-5 d-flex flex-column gap-3">
        <a class="btn btn-success px-3 mx-auto" style="width: fit-content;" href="{% url 'account:register' %}">
            Registrarme
        </a>


        <div class="bg-light shadow py-2 px-3 rounded-3 mx-auto" style=" width:fit-content">
            <a class="small link-offset-3 link-underline link-underline-opacity-0 link-underline-opacity-75-hover"
                href="{% url 'account:password_reset' %}">
                ¿Olvidaste tu contraseña?
            </a>
        </div>
    </div>

</form>

account/templates/partials/profile.html
    <form class="bg-light shadow-lg rounded-3 mt-3 py-4 px-2 text-center" style="--bs-bg-opacity: .9;"
        method="post" id="profile" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="d-flex justify-content-center align-items-center gap-3 mb-3">
            <img id="avatar_img" src="{% if user.Profile.avatar %} {{user.Profile.avatar.url}} {% endif %}"
                class="rounded-circle" style="width: 138px;height:138px; object-fit:contain; background-color: #1e2e33;"
                alt="avatar">

            <div>
                <small class="text-secondary">Nombre de usuario:</small>
                <h3 class="text-light bg-dark bg-gradient rounded-3 p-2">{{user.username}}</h3>
                <input type="file" name="avatar" accept="image/*" id="id_avatar">
                <label id="avatar_label" class="custom-link text-light d-flex align-items-center" for="id_avatar">
                    <svg style="margin-right: 5px;" xmlns="http://www.w3.org/2000/svg" fill="#fff" height="19"
                        viewBox="0 -960 960 960" width="19">
                        <path
                            d="M440-320v-326L336-542l-56-58 200-200 200 200-56 58-104-104v326h-80ZM240-160q-33 0-56.5-23.5T160-240v-120h80v120h480v-120h80v120q0 33-23.5 56.5T720-160H240Z" />
                    </svg>
                    cambiar imagen
                </label>
            </div>

        </div>


        <div class="container my-4">
            <div class="input-group mb-3">
                <span class="input-group-text"> {{ form.first_name.label_tag }}</span>
                {{ form.first_name }}
                <span class="small text-danger"> {{ form.first_name.errors }} </span>

            </div>
            <div class="input-group mb-3">
                <span class="input-group-text"> {{ form.last_name.label_tag }}</span>
                {{ form.last_name }}
                <span class="small text-danger"> {{ form.last_name.errors }} </span>
            </div>
            <div class="input-group mb-3">
                <span class="input-group-text text-truncate"> {{ form.email.label_tag }}</span>
                {{ form.email }}
                <span class="small text-danger"> {{ form.email.errors }} </span>
            </div>
        </div>


        <a class="link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover"
            href="{% url 'account:change_password' %}">
            Cambiar contraseña
        </a>



        <div class="mt-4">
            <input type="button" value="Editar perfil" id="edit_profile" class="btn btn-outline-primary me-2">
            <input type="submit" value="Guardar cambios" class="btn btn-primary">
        </div>

    </form>

account/templates/partials/register.html
<div class="row w-100 m-0">
    <form action="" method="POST" class="text-center my-2 mx-auto col-12 col-md-6">
        {% csrf_token %}


    <h3 class="mb-4 rounded-4  p-2 bg-dark bg-gradient text-light">Datos Personales</h3>
    <div class="container mb-4">
        <div class="d-flex  justify-content-between">

            <div class="form-floating mb-2" style="width: 49%;">
                {{ form.first_name }}
                {{ form.first_name.label_tag }}
                <span class="small text-danger mt-1"> {{ form.first_name.errors }} </span>
            </div>

            <div class="form-floating" style="width: 49%;">
                {{ form.last_name }}
                {{ form.last_name.label_tag }}
                <span class="small text-danger mt-1"> {{ form.last_name.errors }} </span>
            </div>

        </div>

        <div class="form-floating mb-2">
            {{ form.email }}
            {{ form.email.label_tag }}
            <span class="small text-danger mt-1"> {{ form.email.errors }} </span>
        </div>
    </div>
    <hr>
    <h3  class="mb-4 rounded-4  p-2 bg-dark bg-gradient text-light">Datos de Ingreso</h3>
    <div class="container mb-4">
        <div class="form-floating">
            <input type="text" class="form-control mb-2 {% if form.username.errors %}is-invalid{% endif %}"
                maxlength="150" autocomplete="off" name="username" id="id_username" placeholder=""
                value="{% if form.instance.username %}{{ form.instance.username }}{% endif %}">
            {{form.username.label_tag}}
            <span class="small text-danger"> {{form.username.errors}} </span>
        </div>

        <div class="form-floating">
            <input type="password"
                class="form-control mb-2 {% if form.password1.errors or form.password2.errors %}is-invalid{% endif %}"
                name="password1" autocomplete="new-password" id="id_password1" placeholder="password">
            {{form.password1.label_tag}}
            <span class="small text-danger"> {{form.password1.errors}} </span>
        </div>

        <div class="form-floating">
            <input
                class="form-control mb-2 {% if form.password1.errors or form.password2.errors %}is-invalid{% endif %}"
                type="password" name="password2" autocomplete="new-password" id="id_password2" placeholder="password">
            {{form.password2.label_tag}}
            <span class="small text-danger"> {{form.password2.errors}} </span>
        </div>
    </div>
    <hr>

    <input type="submit" value="Registrarme" class="btn btn-success mt-2 px-3">


    <div class="container text-center mt-5">
        <a class="btn btn-primary px-3"
            href="{% url 'account:login' %}">
            Iniciar Sesión
        </a>
    </div>
</form>
</div>