my_site/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

handler404 = "pages.views.handler404"
from django.urls import re_path

# from django.conf import settings
from django.views.static import serve

url_files = [
    re_path(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
    re_path(r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_ROOT}),
]

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("pages.urls")),
    path("apuntes/", include("study_hub.urls")),
    path("cuenta/", include("account.urls")),
    path("cursos/", include("study_manager.urls")),
    path("tinymce/", include("tinymce.urls")),
]

if settings.DEBUG == False:
    urlpatterns += url_files
else:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from .views import home, searchNavbar, about_me


urlpatterns = [
    path("", home, name="home"),
    path("acerca-de-mi/", about_me, name="about"),
    # POST require
    path("search/publications/", searchNavbar, name="search"),
    # GET require
]

study_manager/urls.py
from django.urls import path
from .views.views import *
from .views.course_views import *

app_name = "study_manager"

urlpatterns = [
    # Cursos
    path("", CourseListView.as_view(), name="course_list"),
    path("agregar-curso/", CourseCreateView.as_view(), name="course_add"),
    path("<int:pk>/editar-curso/", CourseUpdateView.as_view(), name="course_edit"),
    path("<int:pk>/borrar-curso/", CourseDeleteView.as_view(), name="course_delete"),
    path(
        "cambiar-visivilidad/<int:pk>",
        toggle_hidden_course,
        name="toggle_hidden_course",
    ),
    # Faltas / Ausencias
    path(
        "<int:course_id>/asistencias/",
        AbsenceListView.as_view(),
        name="absence_list",
    ),
    path(
        "<int:course_id>/asistencias/agregar/",
        AbsenceCreateView.as_view(),
        name="absence_add",
    ),
    path(
        "<int:course_id>/asistencias/<int:pk>/borrar/",
        AbsenceDeleteView.as_view(),
        name="absence_delete",
    ),
    # Examenes
    path("<int:course_id>/examenes/", ExamListView.as_view(), name="exam_list"),
    path("<int:course_id>/examenes/agregar/", ExamCreateView.as_view(), name="exam_add"),
    path(
        "<int:course_id>/examenes/<int:pk>/editar/",
        ExamUpdateView.as_view(),
        name="exam_update",
    ),
    path(
        "<int:course_id>/examenes/<int:pk>/borrar/",
        ExamDeleteView.as_view(),
        name="exam_delete",
    ),
]

study_manager/models.py
from django.db import models
from django.contrib.auth.models import User


class Course(models.Model):
    name = models.CharField(max_length=100)
    schedule = models.CharField(
        max_length=100, help_text="Ejemplo: Martes 14a18hs, Ma14a18, etc."
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="courses")
    hidden = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Absence(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="absences")
    date = models.DateField()
    reason = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return f"{self.course.name} - {self.date}"


class Exam(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="exams")
    date = models.DateField()
    description = models.CharField(max_length=355, blank=True, null=True)
    grade = models.FloatField(blank=True, null=True)

    def __str__(self):
        return f"{self.course.name} - {self.date} - {self.description}"

study_manager/forms.py
from datetime import date
from django import forms
from .models import Course, Absence, Exam


class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ["name", "schedule"]
        widgets = {
            "name": forms.TextInput(
                attrs={
                    "class": "form-control shadow-sm",
                    "placeholder": "Nombre del curso...",
                    "style": "border-radius: 5px; padding: 10px; font-size: 16px;",
                    "autocomplete": "off",
                },
            ),
            "schedule": forms.TextInput(
                attrs={
                    "class": "form-control shadow-sm",
                    "placeholder": "Horario de cursada...",
                    "style": "border-radius: 5px; padding: 10px; font-size: 16px;",
                    "autocomplete": "off",
                }
            ),
        }


class AbsenceForm(forms.ModelForm):
    class Meta:
        model = Absence
        fields = ["date", "reason"]
        widgets = {
            "date": forms.DateInput(
                attrs={
                    "class": "form-control shadow-sm",
                    "style": "border-radius: 5px; padding: 10px; font-size: 16px;",
                    "type": "date",
                    "value": date.today(),
                },
            ),
            "reason": forms.TextInput(
                attrs={
                    "class": "form-control shadow-sm",
                    "placeholder": "Razón de la falta (opcional)",
                    "style": "border-radius: 5px; padding: 10px; font-size: 16px;",
                    "autocomplete": "off",
                }
            ),
        }


class ExamForm(forms.ModelForm):
    class Meta:
        model = Exam
        fields = ["date", "description", "grade"]
        widgets = {
            "date": forms.DateInput(
                format="%Y-%m-%d",
                attrs={
                    "class": "form-control shadow-sm",
                    "style": "border-radius: 5px; padding: 10px; font-size: 16px;",
                    "type": "date",
                },
            ),
            "description": forms.TextInput(
                attrs={
                    "class": "form-control shadow-sm",
                    "placeholder": "Descripción del examen (opcional)",
                    "style": "border-radius: 5px; padding: 10px; font-size: 16px;",
                    "autocomplete": "off",
                }
            ),
            "grade": forms.NumberInput(
                attrs={
                    "class": "form-control shadow-sm",
                    "placeholder": "Nota del examen (opcional)",
                    "style": "border-radius: 5px; padding: 10px; font-size: 16px;",
                    "min": "0",
                    "max": "10",
                    "step": "0.1",
                    "autocomplete": "off",
                }
            ),
        }

study_manager/views/base_views.py
from study_manager.models import Course


class CourseContext:
    title = None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["course"] = Course.objects.get(
            pk=self.kwargs["course_id"], user=self.request.user
        )
        if self.title:
            context["title"] = self.title + " - " + context["course"].name
        return context

study_manager/views/course_views.py
from django.http import JsonResponse
from ..forms import CourseForm
from django.db.models import Count, Q, Min
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from ..models import Course
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.shortcuts import get_object_or_404
from django.utils import timezone


class CourseListView(LoginRequiredMixin, ListView):
    model = Course
    template_name = "course_list.html"
    context_object_name = "courses"
    extra_context = {"title": "Mis Cursos"}

    def get_queryset(self):
        user_course = Course.objects.filter(user=self.request.user)
        user_course = user_course.annotate(
            absences_count=Count("absences"),
            latest_exam_date=Min(
                "exams__date",
                filter=Q(exams__grade=None) & Q(exams__date__gte=timezone.now().date()),
            ),
        )
        return user_course


class CourseCreateView(LoginRequiredMixin, CreateView):
    model = Course
    form_class = CourseForm
    template_name = "form.html"
    extra_context = {"title": "Agregar Curso"}
    success_url = reverse_lazy("study_manager:course_list")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class CourseUpdateView(LoginRequiredMixin, UpdateView):
    model = Course
    form_class = CourseForm
    template_name = "form.html"
    success_url = reverse_lazy("study_manager:course_list")
    extra_context = {"title": "Editar Curso"}


class CourseDeleteView(LoginRequiredMixin, DeleteView):
    model = Course
    template_name = "course_confirm_delete.html"
    success_url = reverse_lazy("study_manager:course_list")
    extra_context = {"title": "Eliminar Curso"}


@login_required
@require_POST
def toggle_hidden_course(request, pk):
    course = get_object_or_404(Course, pk=pk, user=request.user)
    course.hidden = not course.hidden
    course.save()
    # return redirect(request.META.get("HTTP_REFERER", "redirect_if_referer_not_found"))
    return JsonResponse({"hidden": course.hidden})

study_manager/views/views.py
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from study_manager.views.base_views import CourseContext
from ..models import Course, Absence, Exam
from ..forms import AbsenceForm, ExamForm
from django.contrib.auth.mixins import LoginRequiredMixin


class AbsenceListView(CourseContext, LoginRequiredMixin, ListView):
    model = Absence
    template_name = "absence_list.html"
    context_object_name = "absences"
    title = "Faltas"

    def get_queryset(self):
        course = Course.objects.get(pk=self.kwargs["course_id"], user=self.request.user)
        course = Absence.objects.filter(course=course).order_by("date")
        self.extra_context = {"absences_count": course.__len__()}
        return course


class AbsenceCreateView(CourseContext, LoginRequiredMixin, CreateView):
    model = Absence
    form_class = AbsenceForm
    template_name = "form.html"
    title = "Anotar Falta"

    def form_valid(self, form):
        form.instance.course = Course.objects.get(
            pk=self.kwargs["course_id"], user=self.request.user
        )
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy(
            "study_manager:absence_list", kwargs={"course_id": self.kwargs["course_id"]}
        )


class AbsenceDeleteView(CourseContext, LoginRequiredMixin, DeleteView):
    model = Absence
    template_name = "absence_confirm_delete.html"
    extra_context = {"title": "Eliminar Falta"}

    def get_success_url(self):
        return reverse_lazy(
            "study_manager:absence_list", kwargs={"course_id": self.kwargs["course_id"]}
        )


class ExamListView(CourseContext, LoginRequiredMixin, ListView):
    model = Exam
    template_name = "exam_list.html"
    context_object_name = "exams"
    title = "Exámenes"

    def get_queryset(self):
        course = Course.objects.get(pk=self.kwargs["course_id"], user=self.request.user)
        course_exams = Exam.objects.filter(course=course).order_by("date")
        self.extra_context = {
            "pending_exams_count": course_exams.filter(grade=None).count()
        }
        return course_exams


class ExamCreateView(CourseContext, LoginRequiredMixin, CreateView):
    model = Exam
    form_class = ExamForm
    template_name = "form.html"
    title = "Agendar Examen"

    def form_valid(self, form):
        form.instance.course = Course.objects.get(
            pk=self.kwargs["course_id"], user=self.request.user
        )
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy(
            "study_manager:exam_list", kwargs={"course_id": self.kwargs["course_id"]}
        )


class ExamDeleteView(CourseContext, LoginRequiredMixin, DeleteView):
    model = Exam
    template_name = "exam_confirm_delete.html"
    extra_context = {"title": "Eliminar Examen"}

    def get_success_url(self):
        return reverse_lazy(
            "study_manager:exam_list", kwargs={"course_id": self.kwargs["course_id"]}
        )


class ExamUpdateView(CourseContext, LoginRequiredMixin, UpdateView):
    model = Exam
    form_class = ExamForm
    template_name = "form.html"
    title = "Editar Examen"

    def form_valid(self, form):
        form.instance.course = Course.objects.get(
            pk=self.kwargs["course_id"], user=self.request.user
        )
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy(
            "study_manager:exam_list", kwargs={"course_id": self.kwargs["course_id"]}
        )

study_manager/templates/absence_confirm_delete.html
{% extends 'layout.html' %}

{% block header %}
<h1 class="text-center w-75 m-auto mb-3 py-2 px-4 bg-dark text-light rounded">
    {{title}}
</h1>
{% endblock header%}

{% block content %}
<div class="container w-75 mx-auto">
    <h4 class="px-1 mx-auto text-center" style="max-width: 450px;">
        ¿Estás seguro de que deseas eliminar la asistencia del {{ object.date }}?
    </h4>

    <form method="post">
        {% csrf_token %}

        <div class="container d-flex flex-column gap-2 align-items-center mt-4">
            <button type="submit" class="btn btn-danger" style="width: 200px;">Eliminar</button>
            <a href="{% url 'study_manager:absence_list' course.id %}" class="btn btn-secondary"
                style="width: 200px;">Cancelar</a>
        </div>
    </form>
</div>
{% endblock %}

study_manager/templates/absence_list.html
{% extends 'layout.html' %}

{% load static %}


{% block header %}
<h1 class="text-center w-75 m-auto mb-3 py-2 px-4 bg-dark text-light rounded">
    {{title}}
</h1>


<div class="container d-flex justify-content-between flex-wrap gap-1">
    <a class="custom-link text-light icon-link icon-link-hover link-offset-3 link-underline-light link-underline-opacity-0 link-underline-opacity-75-hover"
        style="--bs-icon-link-transform: translate3d(-.2rem, 0 , 0);" href="{% url 'study_manager:course_list' %}">
        <img class="bi" alt="arrow-back" aria-hidden="true" src="{%static '/images/arrow_back.svg'%}">
        Volver
    </a>

    <a class="custom-link text-light icon-link link-offset-3 link-underline-light link-underline-opacity-0 link-underline-opacity-75-hover"
        href="{% url 'study_manager:absence_add' course.id %}">

        <img class="bi fs-4" alt="add-icon" aria-hidden="true" src="{%static '/images/add.svg'%}">
        Anotar Falta
    </a>
</div>

{% endblock header %}


{% block content %}
<div class="container my-2">
    <h2 class="mt-3 mb-4">Inasistencias:
        <span class="badge bg-warning mb-1 text-dark">
            {{absences_count}}
        </span>
    </h2>

    <div class="table-responsive mx-auto">
        <table class="table table-hover table-warning table-striped align-middle shadow-sm">
            <thead>
                <tr class="table-dark">
                    <th>Fecha</th>
                    <th>Razón</th>
                    <th class="col-1"></th>
                </tr>
            </thead>
            <tbody>
                {% if absences %}
                {% for absence in absences %}
                <tr>
                    <td>{{ absence.date }}</td>
                    <td>
                        {% if absence.reason %}
                        {{ absence.reason }}
                        {% else %}
                        -
                        {% endif %}
                    </td>
                    <td class="col-1">
                        <a href="{% url 'study_manager:absence_delete' course.id absence.pk %}"
                            class="btn btn-danger btn-sm">
                            Eliminar
                        </a>
                    </td>
                </tr>
                {% endfor %}
                {% else %}
                <tr>
                    <td colspan="3" class="text-center">No hay faltas anotadas.</td>
                </tr>
                {% endif %}
            </tbody>
        </table>
    </div>
    <a class="mt-5" href="{% url 'study_manager:exam_list' course.id %}">
        <span class="badge bg-success p-2 text-light fs-6">
            Ver Exámenes
        </span>
    </a>
</div>
{% endblock %}

study_manager/templates/course_confirm_delete.html
{% extends 'layout.html' %}

{% block header %}
<h1 class="text-center w-75 m-auto mb-3 py-2 px-4 bg-dark text-light rounded">
    {{title}}
</h1>
{% endblock header%}

{% block content %}
<div class="container w-75 mx-auto">
    <h4 class="px-1 mx-auto text-center" style="max-width: 450px;">
        ¿Estás seguro de que deseas eliminar la materia "{{ object.name }}"?
    </h4>

    <p class="text-center px-1 my-4"><span class="link-offset-2" style="text-decoration:underline">Horario:</span> "{{ object.schedule }}"</p>

    <p class="text-center px-1">
        <small class="text-muted">Nota: Al eliminar la materia, se eliminar
            también todos los exámenes asociados a ella.
        </small>
    </p>
    <form method="post">
        {% csrf_token %}

        <div class="container d-flex flex-column gap-2 align-items-center mt-4">
            <button type="submit" class="btn btn-danger" style="width: 200px;">Eliminar</button>
            <a href="{%url 'study_manager:course_list'%}" class="btn btn-secondary" style="width: 200px;">Cancelar</a>
        </div>

    </form>
</div>
{% endblock %}

study_manager/templates/course_list.html
{% extends 'layout.html' %}
{% load static %}


{% block header %}
<h1 class="text-center w-75 m-auto mb-3 py-2 px-4 bg-dark text-light rounded">
    {{title}}
</h1>


<div class="container d-flex justify-content-between flex-wrap gap-1">
    <a class="custom-link text-light icon-link icon-link-hover link-offset-3 link-underline-light link-underline-opacity-0 link-underline-opacity-75-hover"
        style="--bs-icon-link-transform: translate3d(-.2rem, 0 , 0);" href="javascript:history.back()">
        <img class="bi" alt="arrow-back" aria-hidden="true" src="{% static '/images/arrow_back.svg' %}">
        Volver
    </a>

    <a class="custom-link text-light icon-link link-offset-3 link-underline-light link-underline-opacity-0 link-underline-opacity-75-hover"
        href="{% url 'study_manager:course_add' %}">

        <img class="bi fs-4" alt="add-icon" aria-hidden="true" src="{% static '/images/add.svg' %}">
        Agregar Curso
    </a>
</div>

{% endblock header %}



{% block content %}
<div class="container">
    <div class="d-flex justify-content-between align-items-center flex-wrap gap-2 my-4">
        {% comment %}
        <!-- {%if courses%} ({{courses | length}}) {%endif%} -->
        {% endcomment %}
        <h2>Administración de cursos</h2>
        <button class="btn btn-dark btn-sm d-flex align-items-center gap-1" id="toggle-hidden-courses">
            <img src="{% static '/images/visibility.svg' %}" alt="eye-icon" class="bi">
            <img src="{% static '/images/visibility_off.svg '%}" alt="eye-off-icon" class="bi d-none">
            <span>Ver</span>materias ocultas
        </button>
    </div>

    <div class="table-responsive">

        {% include 'partials/course_table.html' %}

    </div>

    <div class="text-end">
        <button id="see-all-courses" style="all:unset; cursor: pointer;"
            class="text-mutted my-0 p-1"><small>Organizar</small></button>
    </div>
</div>
{% endblock content %}



{% block scripts %}
<script src="{% static '/study_manager.js' %}"></script>
<script>
    document.addEventListener('DOMContentLoaded', () => {
        const span = document.getElementById('toggle-hidden-courses').lastElementChild

        document.querySelectorAll('.toggle-visibility').forEach((button) => {
            button.addEventListener('click', () => {
                const courseId = button.getAttribute('data-course-id');
                const course = document.querySelector(`.course-${courseId}`)
                const toggleUrl = "{% url 'study_manager:toggle_hidden_course' 123456 %}".replace('123456', courseId);


                fetch(toggleUrl, {
                    method: 'POST',
                    headers: {
                        'X-CSRFToken': '{{ csrf_token }}',
                        'Content-Type': 'application/json'
                    }
                })
                    .then(response => response.json())
                    .then(data => {
                        button.querySelectorAll('.bi')
                            .forEach(icon => {
                                icon.classList.toggle('d-none')
                            });

                        course.classList.toggle('table-info');


                        // Solo ocultamos el curso si NO estamos en modo "Ver materias ocultas"
                        if (span.textContent === 'Ver' && course.classList.contains('table-info')) {
                            course.classList.toggle('d-none');
                        }
                    });
            });
        });
    });
</script>
{% endblock scripts %}

study_manager/templates/exam_confirm_delete.html
{% extends 'layout.html' %}

{% block header %}
<h1 class="text-center w-75 m-auto mb-3 py-2 px-4 bg-dark text-light rounded">
    {{title}}
</h1>
{% endblock header%}

{% block content %}
<div class="container w-75 mx-auto">
    <h4 class="px-1 mx-auto text-center" style="max-width: 450px;">
        ¿Estás seguro de que deseas eliminar el examen del {{ object.date }}?
    </h4>

    {% if object.description %}
    <p class="text-center px-1 my-2">"{{ object.description }}"</p>
    {% endif %}

    <form method="post">
        {% csrf_token %}

        <div class="container d-flex flex-column gap-2 align-items-center mt-4">
            <button type="submit" class="btn btn-danger" style="width: 200px;">Eliminar</button>
            <a href="{% url 'study_manager:exam_list' course.id %}" class="btn btn-secondary"
                style="width: 200px;">Cancelar</a>
        </div>

    </form>
</div>
{% endblock %}

study_manager/templates/exam_list.html
{% extends 'layout.html' %}

{% load static %}


{% block header %}
<h1 class="text-center w-75 m-auto mb-3 py-2 px-4 bg-dark text-light rounded">
    {{title}}
</h1>


<div class="container d-flex justify-content-between flex-wrap gap-1">
    <a class="custom-link text-light icon-link icon-link-hover link-offset-3 link-underline-light link-underline-opacity-0 link-underline-opacity-75-hover"
        style="--bs-icon-link-transform: translate3d(-.2rem, 0 , 0);" href="{% url 'study_manager:course_list' %}">
        <img class="bi" alt="arrow-back" aria-hidden="true" src="{%static '/images/arrow_back.svg'%}">
        Volver
    </a>

    <a class="custom-link text-light icon-link link-offset-3 link-underline-light link-underline-opacity-0 link-underline-opacity-75-hover"
        href="{% url 'study_manager:exam_add' course.id %}">

        <img class="bi fs-4" alt="add-icon" aria-hidden="true" src="{%static '/images/add.svg'%}">
        Agendar Examen
    </a>
</div>

{% endblock header %}


{% block content %}
<div class="container my-2">
    <h2 class="mt-3 mb-4">
        Calificaciones pendientes:
        <span class="badge bg-success mb-1">
            {{pending_exams_count}}
        </span>
    </h2>

    <div class="table-responsive">
        <table class="table table-hover table-success table-striped align-middle shadow-sm">
            <thead>
                <tr class="table-dark">
                    <th>Fecha</th>
                    <th>Descripción</th>
                    <th>Nota</th>
                    <th class="col-1"></th>
                </tr>
            </thead>
            <tbody>
                {% if exams %}
                {% for exam in exams %}
                <tr>
                    <td>{{ exam.date }}</td>
                    <td>
                        {% if exam.description %}
                        {{exam.description }}
                        {% else %}
                        -
                        {% endif %}
                    </td>

                    <td>
                        {% if exam.grade %}
                        {{ exam.grade}}
                        {% else %}
                        -
                        {% endif %}
                    </td>


                    <td class="col-1">
                        <div class="d-flex justify-content-between gap-1">
                            <a style="text-decoration:none; pointer-events: all;" title="Editar Publicación"
                                href="{% url 'study_manager:exam_update' course.id exam.pk %}">
                                <img alt="edit-icon" src="{%static '/images/edit.svg'%}">
                            </a>
                            <a style="text-decoration:none; pointer-events: all;" title="Borrar Publicación"
                                href="{% url 'study_manager:exam_delete' course.id exam.pk %}">
                                <img alt="delete-icon" src="{%static '/images/delete.svg'%}">
                            </a>
                        </div>
                    </td>
                </tr>
                {% endfor %}
                {% else %}
                <tr>
                    <td colspan="4" class="text-center">No hay exámenes pendientes.</td>
                </tr>
                {% endif %}
            </tbody>
        </table>
    </div>

    <a class="mt-5" href="{% url 'study_manager:absence_list' course.id %}">
        <span class="badge bg-warning p-2 text-dark fs-6">
            Ver Faltas
        </span>
    </a>
</div>
{% endblock %}

study_manager/templates/form.html
{% extends 'layout.html' %}
{% load static %}
{% block stylesheet %}
<style>
    label {
        display: none;
    }

    .helptext {
        color: var(--bs-secondary);
        padding-left: 15px;
    }

    .errorlist {
        color: darkred;
    }
</style>
{% endblock stylesheet%}

{% block header %}
<h1 class="text-center w-75 m-auto mb-3 py-2 px-4 bg-dark text-light rounded">
    {{title}}
</h1>


<div class="container">
    <a class="custom-link text-light icon-link icon-link-hover link-offset-3 link-underline-light link-underline-opacity-0 link-underline-opacity-75-hover"
        style="--bs-icon-link-transform: translate3d(-.2rem, 0 , 0);" href="javascript:history.back()">
        <img class="bi" alt="arrow-back" aria-hidden="true" src="{%static '/images/arrow_back.svg'%}">
        Volver
    </a>
</div>
{% endblock header %}


{% block content %}
<div class="container mt-2">
    <form method="post" class="container col-md-5">
        {% csrf_token %}
        {{ form.as_p }}

        <div class="d-flex flex-column gap-2 justify-content-center align-items-center mt-4">
            <button type="submit" class="btn btn-success w-75">Guardar</button>
            <a href="javascript:history.back()" class="btn btn-secondary w-75">Cancelar</a>
        </div>
    </form>
</div>
{% endblock %}