my_site/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

handler404 = "pages.views.handler404"
from django.urls import re_path

# from django.conf import settings
from django.views.static import serve

url_files = [
    re_path(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
    re_path(r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_ROOT}),
]

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("pages.urls")),
    path("apuntes/", include("study_hub.urls")),
    path("cuenta/", include("account.urls")),
    path("cursos/", include("study_manager.urls")),
    path("tinymce/", include("tinymce.urls")),
]

if settings.DEBUG == False:
    urlpatterns += url_files
else:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from .views import home, searchNavbar, about_me


urlpatterns = [
    path("", home, name="home"),
    path("acerca-de-mi/", about_me, name="about"),
    # POST require
    path("search/publications/", searchNavbar, name="search"),
    # GET require
]

study_hub/urls.py
from django.urls import path

from .views.views import study
from .views.comment_views import *
from .views.publication_views import *
from .views.subject_views import *
from .views.career_views import *


app_name = "apuntes"

urlpatterns = [
    # pagina inicial, donde aparece el listado de carreras y materias
    path("", study, name="hub"),
    # pagina para ver todas las publicaciones
    path("publicaciones/", AllPublicationsListView.as_view(), name="all_publications"),
    # CAREER REQUESTS
    path("career/", add_career, name="add_career"),
    path("career/delete/<int:pk>", delete_career, name="delete_career"),
    path("<str:career_title>/update/<int:pk>", update_career, name="update_career"),
    # SUBJECT REQUEST
    path("career/subject/", add_subject, name="add_subject"),
    path(
        "<int:career>/<str:subject_name>/delete/<int:pk>",
        delete_subject,
        name="delete_subject",
    ),
    path(
        "<int:career>/<str:subject>/update/<int:pk>",
        update_subject,
        name="update_subject",
    ),
    # CLASS-BASED VIEWS
    path(
        "<str:subject>/<int:id>/publicaciones",
        PublicationsListView.as_view(),
        name="publications",
    ),
    path(
        "<str:subject>/<int:id>/publicacion/",
        PublicationCreateView.as_view(),
        name="publication_create",
    ),
    path(
        "<str:subject>/<int:id>/publicacion/<int:pk>",
        PublicationDetailView.as_view(),
        name="publication_detail",
    ),
    path(
        "<str:subject>/<int:id>/publicacion/<int:pk>/update",
        PublicationUpdateView.as_view(),
        name="publication_update",
    ),
    path(
        "<str:subject>/<int:id>/publicacion/<int:pk>/delete",
        PublicationDeleteView.as_view(),
        name="publication_delete",
    ),
    # COMMENTS
    path(
        "<str:subject>/<int:s_id>/<int:p_id>/add/comment", add_comment, name="add_comment"
    ),
    path(
        "<str:subject>/<int:s_id>/<int:p_id>/delete/<int:pk>",
        delete_comment,
        name="delete_comment",
    ),
    path(
        "<str:subject>/<int:s_id>/<int:p_id>/update/<int:pk>",
        update_comment,
        name="update_comment",
    ),
    path(
        "cambiar-privacidad/publicacion/<int:pk>/",
        change_post_privacy,
        name="change_post_privacy",
    ),
]

study_hub/forms/career.py
from django import forms
from django.core.validators import MaxValueValidator, MinValueValidator
from study_hub.models import Career


class CareerForm(forms.ModelForm):
    class Meta:
        model = Career
        fields = ["title", "number_of_subjects", "university", "duration"]

    title = forms.CharField(
        max_length=40,
        required=True,
        widget=forms.TextInput(
            attrs={
                "class": "shadow",
                "placeholder": "Nombre de la carrera...",
                "autocomplete": "off",
            }
        ),
    )
    number_of_subjects = forms.IntegerField(
        required=True,
        validators=[MaxValueValidator(100), MinValueValidator(1)],
        widget=forms.NumberInput(
            attrs={
                "class": "shadow",
                "min": 1,
                "max": 99,
                "autocomplete": "off",
                "placeholder": 43,
            }
        ),
        label="Cantidad de materias",
    )
    university = forms.CharField(
        max_length=50,
        required=True,
        widget=forms.TextInput(
            attrs={
                "class": "shadow",
                "placeholder": "Nombre de la Universidad...",
                "autocomplete": "off",
            }
        ),
    )
    duration = forms.DecimalField(
        required=True,
        max_digits=3,
        decimal_places=1,
        help_text="Por ejemplo: 3,5 (tres años y medio)",
        widget=forms.NumberInput(
            attrs={
                "class": "shadow",
                "min": 1,
                "max": 99,
                "autocomplete": "off",
                "placeholder": 3.5,
            }
        ),
        label="Duración de la carrera",
    )

study_hub/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, DeleteView, UpdateView
from django.shortcuts import redirect, render, get_object_or_404

from .forms.subject import SubjectForm
from .forms.career import CareerForm

from .models import Career, Subject, Publication

from django.views.decorators.http import require_POST, require_GET

from django.contrib import messages


# INDEX STUDYHUB
@require_GET
def study(request):
    careers = Career.objects.all().order_by("university")
    subjects = Subject.objects.all().order_by("code")

    query = request.GET.get("career", None)
    career_filter = False

    if query:
        career_filter = Career.objects.filter(id=query)

    careerForm = CareerForm()
    subjectForm = SubjectForm()

    return render(
        request,
        "study.html",
        {
            "title": "Apuntes",
            "careers": careers,
            "career_filter": career_filter,
            "subjects": subjects,
            # FORMS
            "careerForm": careerForm,
            "subjectForm": subjectForm,
        },
    )


# CAREER
@require_POST
def add_career(request):
    careerForm = CareerForm(request.POST)
    if careerForm.is_valid():
        newCareer = Career(
            title=careerForm.cleaned_data.get("title"),
            number_of_subjects=careerForm.cleaned_data.get("number_of_subjects"),
            university=careerForm.cleaned_data.get("university"),
            duration=careerForm.cleaned_data.get("duration"),
        )
        newCareer.save()
        return redirect(reverse_lazy("apuntes:hub"))
    return redirect(reverse_lazy("inicio"))


# SUBJECT
@require_POST
def add_subject(request):
    subjectForm = SubjectForm(request.POST)
    if subjectForm.is_valid():
        description = subjectForm.cleaned_data.get("description")
        newSubject = Subject(
            name=subjectForm.cleaned_data.get("name"),
            code=subjectForm.cleaned_data.get("code"),
            description=description if description else "",
            career=subjectForm.cleaned_data.get("career"),
        )
        newSubject.save()
        return redirect(reverse_lazy("apuntes:hub"))

    return redirect(reverse_lazy("inicio"))


# PUBLICATIONS GENERIC VIEW
# LISTA FILTRADA
class PublicationsListView(ListView):
    model = Publication
    template_name = "list_publications.html"
    context_object_name = "publications"
    # extra_context = {para agregar un parametro del contexto desde la clase}

    # realizo el filtrado obteniendo la query id
    def get_queryset(self):
        return Publication.objects.filter(subject=self.kwargs["id"])

    # agrego valores al contexto
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        subject = get_subject_or_404(self.kwargs["id"], self.kwargs["subject"])

        context["subject"] = subject
        context["title"] = subject.name
        return context


class PublicationDetailView(DetailView):
    model = Publication
    template_name = "publication.html"
    context_object_name = "publication"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        subject = get_subject_or_404(self.kwargs["id"], self.kwargs["subject"])

        context["id"] = subject.id
        context["title"] = subject.name
        return context


class PublicationCreateView(CreateView):
    model = Publication
    fields = ["title", "sub_title", "content", "subject", "image"]
    template_name = "publication.html"

    def get_success_url(self):
        return reverse_lazy(
            "apuntes:publication_detail",
            kwargs={
                "subject": self.kwargs["subject"],
                "id": self.kwargs["id"],
                "pk": self.object.pk,
            },
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        subject = get_subject_or_404(self.kwargs["id"], self.kwargs["subject"])

        context["id"] = subject.id
        context["title"] = subject.name
        return context


class PublicationUpdateView(UpdateView):
    model = Publication
    template_name = "publication.html"
    fields = ["title", "sub_title", "content", "subject", "image"]

    def get_success_url(self):
        return reverse_lazy(
            "apuntes:publication_detail",
            kwargs={
                "subject": self.kwargs["subject"],
                "id": self.kwargs["id"],
                "pk": self.object.pk,
            },
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        subject = get_subject_or_404(self.kwargs["id"], self.kwargs["subject"])

        context["id"] = subject.id
        context["title"] = subject.name
        return context


class PublicationDeleteView(DeleteView):
    model = Publication
    template_name = "publication.html"
    context_object_name = "publication"

    def get_success_url(self):
        return reverse_lazy(
            "apuntes:publications",
            kwargs={"subject": self.kwargs["subject"], "id": self.kwargs["id"]},
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        subject = get_subject_or_404(self.kwargs["id"], self.kwargs["subject"])

        context["id"] = subject.id
        context["title"] = subject.name
        context["delete"] = True
        context["form"] = False
        return context


def get_subject_or_404(id, name):
    return get_object_or_404(Subject, pk=id, name=name)

study_hub/views/career_views.py
from django.views.decorators.http import require_POST
from study_hub.forms.career import CareerForm
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from ..models import Career


@login_required
@require_POST
def add_career(request):
    career_form = CareerForm(request.POST)
    if career_form.is_valid():
        career_form.save()
        title = career_form.cleaned_data.get("title")
        messages.success(request, f"La carrera: {title}, ha sido agregada correctamente!")
        return redirect(reverse_lazy("apuntes:hub"))

    msg = f"Ocurrio un error al intentar agregar la carrera, intentelo nuevamente."
    messages.error(request, msg)
    return redirect(reverse_lazy("apuntes:hub"))


@login_required
def delete_career(request, pk):
    career = get_object_or_404(Career, pk=pk)
    if request.user.is_authenticated and request.user.is_staff:
        career.delete()
        msg = f"La carrera '{career.title}' de {career.university} fue borrada exitosamente."
        messages.success(request, msg)
    else:
        messages.error(request, "No tienes permiso para realizar esta acción.")

    return redirect(reverse_lazy("apuntes:hub"))


@login_required
def update_career(request, career_title, pk):
    if not request.user.is_authenticated and not request.user.is_staff:
        messages.error(request, "No tienes permiso para realizar esta acción.")
        return redirect(reverse_lazy("apuntes:hub"))

    career = get_object_or_404(Career, title=career_title, pk=pk)

    if request.method == "POST":
        form = CareerForm(request.POST, instance=career)
        if form.is_valid():
            form.save()
            msg = f"La carrera '{career_title}' de {career.university} fue editada exitosamente."
            messages.success(request, msg)
        return redirect(reverse_lazy("apuntes:hub"))

    else:
        form = CareerForm(instance=career)
        return render(
            request,
            "study.html",
            {"careerForm": form, "update": "career", "title": "Actualizar Carrera"},
        )

study_hub/views/comment_views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy

from study_hub.forms.comment import CommentForm
from study_hub.views.views import get_subject_or_404
from ..models import Comment, Publication
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.contrib import messages


def _redirect_to_publication_detail(subject_obj, p_id):
    return redirect(
        reverse_lazy(
            "apuntes:publication_detail",
            kwargs={"subject": subject_obj.name, "id": subject_obj.pk, "pk": p_id},
        )
    )


@login_required
@require_POST
def add_comment(request, subject, s_id, p_id):
    subject_obj = get_subject_or_404(s_id, subject)
    publication = get_object_or_404(Publication, pk=p_id)
    comment = request.POST["comment"].strip()

    if len(comment) > 1:
        Comment.objects.create(
            author=request.user, publication=publication, comment=comment
        )

    return _redirect_to_publication_detail(subject_obj, p_id)


@login_required
def delete_comment(request, subject, s_id, p_id, pk):
    comment = get_object_or_404(Comment, pk=pk, publication=p_id)
    subject_obj = get_subject_or_404(s_id, subject)

    if comment.author == request.user:
        comment.delete()
        messages.success(request, "Tu comentario ha sido eliminado!")
    else:
        messages.error(request, "No puedes eliminar un comentario de otra persona!")

    return _redirect_to_publication_detail(subject_obj, p_id)


@login_required
def update_comment(request, subject, s_id, p_id, pk):
    comment_obj = get_object_or_404(Comment, pk=pk, publication=p_id)
    subject_obj = get_subject_or_404(s_id, subject)
    publication_obj = get_object_or_404(Publication, pk=p_id)

    if request.method == "POST" and comment_obj.author == request.user:
        comment_form = CommentForm(request.POST, instance=comment_obj)
        if comment_form.is_valid:
            comment_form.save()
            messages.success(request, "Tu comentario ha sido actualizado correctamente!")

        return _redirect_to_publication_detail(subject_obj, p_id)

    comment_form = CommentForm(instance=comment_obj)

    return render(
        request,
        "publication.html",
        {
            "id": subject_obj.id,
            "title": subject_obj.name,
            "comments": Comment.objects.filter(publication=p_id),
            "new_comment": CommentForm(),
            "edit_comment_form": comment_form,
            "id_comment_form": comment_obj.pk,
            "publication": publication_obj,
        },
    )

study_hub/views/publication_base_views.py
from study_hub.models import Publication
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.core.paginator import EmptyPage, PageNotAnInteger
from urllib.parse import urlencode
from django.urls import reverse_lazy


def _success_url(self):
    base_url = reverse_lazy(
        "apuntes:publication_detail",
        kwargs={
            "subject": self.kwargs["subject"],
            "id": self.kwargs["id"],
            "pk": self.object.pk,
        },
    )
    query_params = urlencode({"publicacion": "nueva"})
    return f"{base_url}?{query_params}"


class PublicationTemplateNameMixin:
    template_name = "publication.html"


class PaginatedListView(ListView):
    context_object_name = "publications"
    model = Publication
    paginate_by = 10

    def paginate_queryset(self, queryset, page_size):
        paginator = self.get_paginator(queryset, page_size)
        page = self.request.GET.get("page")

        try:
            page_number = int(page)
        except (TypeError, ValueError):
            page_number = 1

        try:
            page_obj = paginator.page(page_number)
        except (EmptyPage, PageNotAnInteger):
            page_obj = paginator.page(paginator.num_pages)

        return (paginator, page_obj, page_obj.object_list, page_obj.has_other_pages())


class CreateViewWithSuccessURL(PublicationTemplateNameMixin, CreateView):
    model = Publication

    def get_success_url(self):
        return _success_url(self)


class UpdateViewWithSuccessURL(PublicationTemplateNameMixin, UpdateView):
    model = Publication

    def get_success_url(self):
        return _success_url(self)


class DeleteViewWithSuccessURL(PublicationTemplateNameMixin, DeleteView):
    model = Publication

    def get_success_url(self):
        return reverse_lazy(
            "apuntes:publications",
            kwargs={"subject": self.kwargs["subject"], "id": self.kwargs["id"]},
        )

study_hub/templates/partials/career_form.html
<form id="career_form" method="POST" action="{% if not update %} {% url 'apuntes:add_career' %} {% endif %}"
  class="d-flex flex-column mx-auto shadow-lg rounded py-3 px-4">
  {% csrf_token %}

  {% if not update %}
  <div class="d-flex justify-content-between align-items-center">
    <span class="fs-4 text-center">Agregar Carrera</span>
    <button id="close_modal" type="button" class="btn btn-danger py-1 shadow">X</button>
  </div>

  {% endif %}

  {{ careerForm.university }}
  {{ careerForm.title }}


  <div class="inputWithLabel d-flex justify-content-between align-items-center">
    <label for="{{ careerForm.number_of_subjects.id_for_label }}">{{careerForm.number_of_subjects.label }}:</label>
    {{ careerForm.number_of_subjects }}
  </div>

  <div>
    <div class="inputWithLabel d-flex justify-content-between align-items-center">
      <label for="{{ careerForm.duration.id_for_label }}">{{careerForm.duration.label }}:</label>
      {{ careerForm.duration }}
    </div>

    <span class="container-fluid text-center">
      <small class="text-body-tertiary">{{ careerForm.duration.help_text }}</small>
    </span>
  </div>
  <button type="submit" class="btn btn-primary mt-1">
    {% if update %} Actualizar {% else %} Agregar{% endif %}
  </button>

  
  {% if update %}
  <a href="{% url 'apuntes:hub' %}" class="btn btn-danger mb-2">Cancelar</a>
  {% endif %}
    
</form>

study_hub/templates/partials/comments.html
<div class="mt-4 d-flex flex-column gap-3">
  
  <h4 class="text-center text-light rounded w-50 mx-auto bg-dark p-2" style="--bs-bg-opacity: .85;">
    {% if comments|length >= 1%}
    Comentarios {% else %}No hay comentarios{% endif %}
  </h4>
  {% for comment in comments %}


  {% if comment.id == id_comment_form %}
  {% comment %} FORMULARIO PARA ACTUALIZAR EL COMENTARIO {% endcomment %}

  <div id="comment-{{comment.pk}}" class="container-fluid mt-3" id="">
    <form action="" method="POST">
      {% csrf_token %}
      <div class="d-flex justify-content-center">
        {{edit_comment_form.comment}}
      </div>
      <div class="text-end" style="width: 95%">
        <a href="{% url 'apuntes:publication_detail' subject=title id=id pk=publication.pk%}#comment-{{comment.pk}}"
          class="btn btn-danger me-3">Cancelar</a>
        <input type="submit" value="Actualizar Comentario" class="btn btn-dark my-4">
      </div>
    </form>
  </div>

  {% else %}

  <div id="comment-{{comment.pk}}" class="comment container rounded">
    <div class="d-flex justify-content-start gap-2 align-items-center py-3">
      <img id="avatar_img" src="{{ comment.author.Profile.avatar.url }}" class="rounded-circle"
        style="width: 45px;height:45px; object-fit:contain; background-color: #1e2e33;" alt="avatar">
      <h5 class="text-truncate"> {{ comment.author.first_name }} {{ comment.author.last_name }}:</h5>
    </div>
    <div class="px-1">
      {{comment.comment|safe}}
    </div>
    <p class="text-end text-secondary mb-0"><small> {{comment.comment_date}}</small></p>

    {% if comment.author == user %}

    <div class="text-end my-2">
      <a href="{% url 'apuntes:update_comment' subject=title s_id=id p_id=publication.id pk=comment.pk %}#comment-{{comment.pk}}"
        class="small me-2 link-info">Editar</a>
      <a href="{% url 'apuntes:delete_comment' subject=title s_id=id p_id=publication.id pk=comment.pk %}"
        class="small me-2 link-danger">Borrar</a>
    </div>

    {% endif %}

  </div>

  {% endif %}
  {% endfor %}


  {% if user.is_authenticated and not edit_comment_form %}
  <div class="container-fluid mt-3">
    <form action="{% url 'apuntes:add_comment' subject=title s_id=id p_id=publication.id %}" method="POST">
      {% csrf_token %}
      <div class="d-flex justify-content-center">
        {{new_comment.comment}}
      </div>
      <div class="text-end" style="width: 95%">
        <input type="submit" value="Comentar" class="btn btn-dark my-4">
      </div>
    </form>
  </div>
  {% else %}
  <p class="fs-5 fw-light text-center mt-3 mx-auto">Inicia sesion para escribir un comentario!</p>
  {% endif %}


</div>

study_hub/templates/partials/pagination.html
<div class="container d-flex align-items-center justify-content-between overflow-x-hidden">
    <div class="d-flex align-items-center gap-1">

        <div class="bg-danger bg-gradient p-2 rounded {% if not page_obj.has_previous %} opacity-50  {% endif %}">
            <a href="
            {% if page_obj.has_previous %}
            ?page=1
            {% else %}
            #
            {% endif %}
            " class="link-light px-2 text-decoration-none">
                &laquo;
            </a>
        </div>

        <div class="nowrap text-truncate bg-danger bg-gradient p-2 rounded {% if not page_obj.has_previous %} opacity-50  {% endif %}">
            <a href="
            {% if page_obj.has_previous %}
            ?page={{ page_obj.previous_page_number }}
            {% else %}
            #
            {% endif %}
            " class="link-light px-2 text-decoration-none">
                Anterior
            </a>
        </div>
    </div>

    <div class="bg-danger bg-gradient text-light p-2 rounded nowrap text-truncate">
        <span class="d-none d-md-inline"> Página</span> {{ page_obj.number }} de {{ paginator.num_pages }}
    </div>

    <div class="d-flex align-items-center gap-1">
        <div class="nowrap text-truncate bg-danger bg-gradient p-2 rounded {% if not page_obj.has_next %} opacity-50  {% endif %}">
            <a href="
            {% if page_obj.has_next %}
            ?page={{ page_obj.next_page_number }}
            {% else %}
            #
            {% endif %}
            " class="link-light px-2 text-decoration-none">
                Siguiente
            </a>
        </div>

        <div class="bg-danger bg-gradient p-2 rounded {% if not page_obj.has_next %} opacity-50  {% endif %}">
            <a href="
            {% if page_obj.has_next %}
            ?page={{ page_obj.paginator.num_pages }}
            {% else %}
            #
            {% endif %}
            " class="link-light px-2 text-decoration-none">
                &raquo;
            </a>
        </div>
    </div>
</div>

study_hub/templates/partials/publication_form.html
{% load static %}
<form method="POST" action="" style="width: 100%;height: auto;">
  {% csrf_token %}
  {{ form.media }}
  <input class="fs-2 fw-semibold px-2 my-2 rounded input_id_title" autocomplete="off" id="id_title" type="text"
    placeholder="Escriba su título principal..." name="title" maxlength="60"
    value="{% if form.instance.title %}{{ form.instance.title }}{% endif %}">
  {{form.title.errors}}

  <div class="publication_content px-2 my-2">
    {{form.content}}
    {{ form.content.errors }}
  </div>


  <div class="container d-flex justify-content-between text-center mx-auto gap-2 my-4" style="flex-wrap: wrap;">
    <div class="d-flex align-items-center gap-2">
      <label for="id_subject" class="text-end text-nowrap" style="width: 60px;">Materia:</label>
      <select name="subject" class="form-select-sm" style="width:200px;" id="id_subject">
        <option selected value="{{id}}">{{title}}</option>
      </select>
      {{form.subject.errors}}
    </div>

    <div class="d-flex align-items-center gap-2">
      <label for="id_author" class="text-end text-nowrap" style="width: 60px;">Autor:</label>
      <select name="author" class="form-select-sm" style="width:200px;" id="id_author">
        <option selected value="{{user.id}}">{{user.first_name}} {{user.last_name}}</option>
      </select>
      {{form.author.errors}}
    </div>

    <div class="d-flex align-items-center gap-2" style="padding-left: calc(60px + .5rem);">
      <select name="isPrivate" id="id_isPrivate" class="form-select-sm" style="width:200px;">
        <option {% if not form.instance.isPrivate %} selected {% endif %} value="{{False}}">
          🌍 Público
        </option>

        <option {% if form.instance.isPrivate %} selected {% endif %} value="{{True}}">
          🔒 Privado
        </option>
      </select>
    </div>

  </div>

  <div class="text-center my-3">
    {% if form.instance.content %}
    <a class="btn btn-danger me-2" href="{% url 'apuntes:publication_detail' subject=title id=id pk=publication.pk %}">
      Cancelar
    </a>
    {% endif %}
    <input class="btn btn-primary" type="submit"
      value="{% if form.instance.content %}Actualizar{% else %}Publicar{% endif %}">
  </div>
</form>

study_hub/templates/partials/subject_form.html
<div {% if not update %} hidden {% endif %}
    class="form_container container-fluid text-center my-2 bg-light bg-gradient p-3 rounded-4">
    {% if not update %}
    <div class="d-flex justify-content-between align-items-center mb-4">
        <span class="fs-4 text-center mx-auto">Agregar Materia</span>
        <button type="button" class="btn_close_form_subject btn btn-danger py-1">X</button>
    </div>
    {% endif %}

    <form id="subject_form" method="POST" class="mx-auto"
        action="{% if not update %} {% url 'apuntes:add_subject' %} {% endif %}">
        {% csrf_token %}
        {{subjectForm}}
        {% if update %}
        <a href="{% url 'apuntes:hub' %}" class="btn btn-danger mt-2 me-2">Cancelar</a>
        {% endif %}
        <input type="submit" class="btn btn-primary mt-2 mx-auto"
            value="{% if update %}Actualizar{% else %}Agregar{% endif %}">
    </form>
</div>