account/urls.py
from django.urls import path
from .views import (
    change_password,
    login_request,
    logout_request,
    my_publications,
    profile_request,
    register_request,
    CustomPasswordReset,
    CustomPasswordResetDone,
    CustomPasswordResetConfirm,
    CustomPasswordResetComplete,
)

app_name = "account"
password_reset_config = [
    # EMAIL
    path("restablecer-contraseña", CustomPasswordReset.as_view(), name="password_reset"),
    # MSG
    path(
        "restablecer-contraseña-enviado",
        CustomPasswordResetDone.as_view(),
        name="password_reset_done",
    ),
    # NEW_PASSWORD1 AND NEW_PASSWORD2
    path(
        "restablecer-contraseña/<uidb64>/<token>/",
        CustomPasswordResetConfirm.as_view(),
        name="password_reset_confirm",
    ),
    # MSG
    path(
        "restablecer-contraseña/finalizado",
        CustomPasswordResetComplete.as_view(),
        name="password_reset_complete",
    ),
]


urlpatterns = [
    path("iniciar-sesion/", login_request, name="login"),
    path("registrarse/", register_request, name="register"),
    path("perfil/", profile_request, name="profile"),
    path("cambiar-contraseña/", change_password, name="change_password"),
    path("cerrar-sesion/", logout_request, name="logout"),
    path("mis-publicaciones/", my_publications, name="my_publications"),
    *password_reset_config,
]

my_site/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

handler404 = "pages.views.handler404"
from django.urls import re_path

# from django.conf import settings
from django.views.static import serve

url_files = [
    re_path(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
    re_path(r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_ROOT}),
]

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("pages.urls")),
    path("apuntes/", include("study_hub.urls")),
    path("cuenta/", include("account.urls")),
    path("cursos/", include("study_manager.urls")),
    path("tinymce/", include("tinymce.urls")),
]

if settings.DEBUG == False:
    urlpatterns += url_files
else:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from .views import home, searchNavbar, about_me


urlpatterns = [
    path("", home, name="home"),
    path("acerca-de-mi/", about_me, name="about"),
    # POST require
    path("search/publications/", searchNavbar, name="search"),
    # GET require
]

study_hub/urls.py
from django.urls import path

from .views.views import study
from .views.comment_views import *
from .views.publication_views import *
from .views.subject_views import *
from .views.career_views import *


app_name = "apuntes"

urlpatterns = [
    # pagina inicial, donde aparece el listado de carreras y materias
    path("", study, name="hub"),
    # pagina para ver todas las publicaciones
    path("publicaciones/", AllPublicationsListView.as_view(), name="all_publications"),
    # CAREER REQUESTS
    path("career/", add_career, name="add_career"),
    path("career/delete/<int:pk>", delete_career, name="delete_career"),
    path("<str:career_title>/update/<int:pk>", update_career, name="update_career"),
    # SUBJECT REQUEST
    path("career/subject/", add_subject, name="add_subject"),
    path(
        "<int:career>/<str:subject_name>/delete/<int:pk>",
        delete_subject,
        name="delete_subject",
    ),
    path(
        "<int:career>/<str:subject>/update/<int:pk>",
        update_subject,
        name="update_subject",
    ),
    # CLASS-BASED VIEWS
    path(
        "<str:subject>/<int:id>/publicaciones",
        PublicationsListView.as_view(),
        name="publications",
    ),
    path(
        "<str:subject>/<int:id>/publicacion/",
        PublicationCreateView.as_view(),
        name="publication_create",
    ),
    path(
        "<str:subject>/<int:id>/publicacion/<int:pk>",
        PublicationDetailView.as_view(),
        name="publication_detail",
    ),
    path(
        "<str:subject>/<int:id>/publicacion/<int:pk>/update",
        PublicationUpdateView.as_view(),
        name="publication_update",
    ),
    path(
        "<str:subject>/<int:id>/publicacion/<int:pk>/delete",
        PublicationDeleteView.as_view(),
        name="publication_delete",
    ),
    # COMMENTS
    path(
        "<str:subject>/<int:s_id>/<int:p_id>/add/comment", add_comment, name="add_comment"
    ),
    path(
        "<str:subject>/<int:s_id>/<int:p_id>/delete/<int:pk>",
        delete_comment,
        name="delete_comment",
    ),
    path(
        "<str:subject>/<int:s_id>/<int:p_id>/update/<int:pk>",
        update_comment,
        name="update_comment",
    ),
    path(
        "cambiar-privacidad/publicacion/<int:pk>/",
        change_post_privacy,
        name="change_post_privacy",
    ),
]

study_manager/urls.py
from django.urls import path
from .views.views import *
from .views.course_views import *

app_name = "study_manager"

urlpatterns = [
    # Cursos
    path("", CourseListView.as_view(), name="course_list"),
    path("agregar-curso/", CourseCreateView.as_view(), name="course_add"),
    path("<int:pk>/editar-curso/", CourseUpdateView.as_view(), name="course_edit"),
    path("<int:pk>/borrar-curso/", CourseDeleteView.as_view(), name="course_delete"),
    path(
        "cambiar-visivilidad/<int:pk>",
        toggle_hidden_course,
        name="toggle_hidden_course",
    ),
    # Faltas / Ausencias
    path(
        "<int:course_id>/asistencias/",
        AbsenceListView.as_view(),
        name="absence_list",
    ),
    path(
        "<int:course_id>/asistencias/agregar/",
        AbsenceCreateView.as_view(),
        name="absence_add",
    ),
    path(
        "<int:course_id>/asistencias/<int:pk>/borrar/",
        AbsenceDeleteView.as_view(),
        name="absence_delete",
    ),
    # Examenes
    path("<int:course_id>/examenes/", ExamListView.as_view(), name="exam_list"),
    path("<int:course_id>/examenes/agregar/", ExamCreateView.as_view(), name="exam_add"),
    path(
        "<int:course_id>/examenes/<int:pk>/editar/",
        ExamUpdateView.as_view(),
        name="exam_update",
    ),
    path(
        "<int:course_id>/examenes/<int:pk>/borrar/",
        ExamDeleteView.as_view(),
        name="exam_delete",
    ),
]

pages/templates/partials/navbar.html
{% load static %}
<nav class="navbar navbar-expand-md  navbar-dark bg-dark" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand p-0" href="{% url 'home' %}">
      <img src="{%static 'images/logo.webp'%}" class="image-logo" alt="logo">
      StudyHub
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <ul class="navbar-nav ms-auto">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'apuntes:all_publications' %}">Publicaciones</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'apuntes:hub' %}">Materias</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'study_manager:course_list' %}">Mis Cursos</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-capitalize" href="#" role="button" data-bs-toggle="dropdown"
            aria-expanded="false">
            {{user.first_name}}
          </a>

          <ul class="dropdown-menu">
            <li><a class="dropdown-item py-2" href="{% url 'account:profile' %}">Mi Perfil</a></li>
            <li><a class="dropdown-item py-2" href="{% url 'account:my_publications' %}">Mis Publicaciones</a></li>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li><a class="dropdown-item py-2" id="logout" href="{% url 'account:logout' %}">Cerrar Sesión</a></li>
          </ul>


        <li class="nav-item dropdown" role="search">
          {% csrf_token %}
          <input id="search" autocomplete="off" class="form-control nav-link px-3 " type="search"
            placeholder="Buscar publicación..." aria-label="Search">
          <ul class="dropdown-menu container position-absolute" id="dropdown">

          </ul>
        </li>
        </li>

        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account:login' %}">Iniciar Sesión</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account:register' %}">Registrarme</a>
        </li>
        {% endif %}
      </ul>

    </div>
  </div>
</nav>